### ISSUE TITLE
about the number of classes

### ISSUE THREAD

**Issue by jiejiangd** [harveerar/PSIGAN#1]
Hello, thank you very much for sharing the code. I would like to ask what should be modified if there are only two categories, background and target. I only modified self.num_organ=2, but the error was still reported in the end

**Comment by overbestfitting** [comment]
Hi, Would you please post the error here?

I guess if there is only background and target, your max-label value should be 1.
Probably this is the error.

**Comment by jiejiangd** [comment]
/media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
&nbsp; warnings.warn(warning.format(ret))
/opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [27,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [29,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [30,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed.
/opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [31,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed.
Traceback (most recent call last):
&nbsp; File "train_PSIGAN.py", line 121, in <module&gt;
&nbsp; &nbsp; model.optimize_parameters()
&nbsp; File "/media/s2/hyj/seg/models/PSIGAN_model.py", line 596, in optimize_parameters
&nbsp; &nbsp; self.backward_G()
&nbsp; File "/media/s2/hyj/seg/models/PSIGAN_model.py", line 549, in backward_G
&nbsp; &nbsp; loss_G.backward()
&nbsp; File "/media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward
&nbsp; &nbsp; torch.autograd.backward(self, gradient, retain_graph, create_graph)
&nbsp; File "/media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
&nbsp; &nbsp; allow_unreachable=True)&nbsp; # allow_unreachable flag
RuntimeError: CUDA error: device-side assert triggered

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by overbestfitting** [comment]
As I have mentioned, if you have two class ( one for background and one for foreground), the max value of your source label should be 1. The error above showed your max label value is larger than 1.  If you are using the example data in the source code, you should do  "source_label[source_label>1]=1".  Then it should work. 
Good Luck!

> /media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/nn/_reduction.py:43: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead. &nbsp; warnings.warn(warning.format(ret)) /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [27,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed. /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [28,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed. /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [29,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed. /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [30,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed. /opt/conda/conda-bld/pytorch_1570910687230/work/aten/src/THCUNN/ClassNLLCriterion.cu:106: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [31,0,0] Assertion `t &gt;= 0 &amp;&amp; t < n_classes` failed. Traceback (most recent call last): &nbsp; File "train_PSIGAN.py", line 121, in <module&gt; &nbsp; &nbsp; model.optimize_parameters() &nbsp; File "/media/s2/hyj/seg/models/PSIGAN_model.py", line 596, in optimize_parameters &nbsp; &nbsp; self.backward_G() &nbsp; File "/media/s2/hyj/seg/models/PSIGAN_model.py", line 549, in backward_G &nbsp; &nbsp; loss_G.backward() &nbsp; File "/media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 150, in backward &nbsp; &nbsp; torch.autograd.backward(self, gradient, retain_graph, create_graph) &nbsp; File "/media/s2/hyj/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward &nbsp; &nbsp; allow_unreachable=True)&nbsp; # allow_unreachable flag RuntimeError: CUDA error: device-side assert triggered &nbsp; &nbsp; ------------------&nbsp;Original&nbsp;------------------ From: &nbsp;"overbestfitting"<notifications@github.com&gt;; Date: &nbsp;Thu, Aug 13, 2020 03:45 AM To: &nbsp;"harveerar/PSIGAN"<PSIGAN@noreply.github.com&gt;; Cc: &nbsp;"jiejiangd"<201821562004@smail.xtu.edu.cn&gt;; "Author"<author@noreply.github.com&gt;; Subject: &nbsp;Re: [harveerar/PSIGAN] about the number of classes (#1) &nbsp; Hi, Would you please post the error here? I guess if there is only background and target, your max-label value should be 1. Probably this is the error. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jiejiangd** [comment]
It's done. Thank you
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by 201521190031** [comment]
After modifying self.num_organ=2, I still obtain dice_score=0(%) on the validation set of Brats 2018 dataset. Could you give me the answer.
